### ISSUE TITLE
Plugin generates error with Rails 3.2

### ISSUE THREAD

**Issue by astudnev** [electronick/enum_column#11]
c:/idjet/Ruby192/lib/ruby/gems/1.9.1/gems/enum_column3-0.1.3/lib/enum/enum_adapter.rb:8:in `<top (required)>': uninitialized constant ActiveRecord::ConnectionAdapters::Mysq
lColumn (NameError)
        from c:/idjet/Ruby192/lib/ruby/gems/1.9.1/gems/enum_column3-0.1.3/lib/enum_column.rb:6:in`block (2 levels) in class:EnumColumnRailtie'
        from c:/idjet/Ruby192/lib/ruby/gems/1.9.1/gems/activesupport-3.2.1/lib/active_support/lazy_load_hooks.rb:36:in `instance_eval'
        from c:/idjet/Ruby192/lib/ruby/gems/1.9.1/gems/activesupport-3.2.1/lib/active_support/lazy_load_hooks.rb:36:in`execute_hook'
        from c:/idjet/Ruby192/lib/ruby/gems/1.9.1/gems/activesupport-3.2.1/lib/active_support/lazy_load_hooks.rb:43:in `block in run_load_hooks'

**Comment by sergey-homenko** [comment]
I have the same problem: uninitialized constant ActiveRecord::ConnectionAdapters::MysqlColumn
Rails 3.2, Ruby 1.9.3

**Comment by mkon** [comment]
can confirm this, running rails 3.2.1 on ruby 1.9.3-p0

**Comment by flipkick** [comment]
Fix: https://github.com/electronick/enum_column/pull/9

**Comment by electronick** [comment]
It works now, thanks @flipkick !
