### ISSUE TITLE
Does not seem to work with `validates :gender, :inclusion => { :in => %w{male female} }`

### ISSUE THREAD

**Issue by jmuheim** [electronick/enum_column#14]
I banged my head against the screen while trying to get `validates :gender, :inclusion => { :in => %w{male female} }` to work, while :gender was an :enum field. But validations just don't pass. When doing the same with a normal :string field, everything works.

Migration:

```
class CreatePlayers < ActiveRecord::Migration
  def change
    create_table :players do |t|
      t.string :name
      t.enum :gender, :limit => [:male, :female], :default => :male
      t.string :gender2

      t.timestamps
    end
  end
end
```

Model:

```
class Player < ActiveRecord::Base
  validates :gender, :inclusion => { :in => %w{male female} }
  validates :gender2, :inclusion => { :in => %w{male female} }
end
```

Here some code which demonstrates the problem:

```
1.9.3p0 :001 > p = Player.new
 => #<Player id: nil, name: nil, gender: :male, gender2: nil, created_at: nil, updated_at: nil> 
1.9.3p0 :002 > p.valid?
 => false 
1.9.3p0 :003 > p.errors
 => #<ActiveModel::Errors:0x007ff55601e1d8 @base=#<Player id: nil, name: nil, gender: :male, gender2: nil, created_at: nil, updated_at: nil>, @messages={:gender=>["ist nicht in der Liste vorhanden!"], :gender2=>["ist nicht in der Liste vorhanden!"]}> 
1.9.3p0 :004 > p.gender = 'male'
 => "male" 
1.9.3p0 :005 > p.gender2 = 'male'
 => "male" 
1.9.3p0 :006 > p.valid?
 => false 
1.9.3p0 :007 > p.errors
 => #<ActiveModel::Errors:0x007ff55601e1d8 @base=#<Player id: nil, name: nil, gender: :male, gender2: "male", created_at: nil, updated_at: nil>, @messages={:gender=>["ist nicht in der Liste vorhanden!"]}>
```

**Comment by electronick** [comment]
Yep, I was going to recommend something like

validates :gender, :inclusion => { :in => %w{male female}.map(&:to_sym) }
or just
validates_columns :gender
but it's good to know you've solved it.

So closing issue, not sure about is it possible to delete it, I don't see any buttons for it.

**Comment by jmuheim** [comment]
Thanks! Is there a Rails3 style validation equivalent? Like `validates :gender, :enum`?

**Comment by jmuheim** [comment]
Still, I just don't get the RSpec tests to work:

```
it { should validate_inclusion_of(:gender).in([:male, :female]) }
```

results in

```
Expected Contact to be valid when gender is set to [:male, :female]
```

**Comment by electronick** [comment]
You should use old fashion for now.
Honestly, I never validate enum columns as their values can't be other than :limit values in db (especially when you set :null => false for the column), but still I don't see any reasons why rspec matchers shouldn't work.

**Comment by electronick** [comment]
Need to test it a bit.

**Comment by jmuheim** [comment]
I also wrote a thread about this problem on StackOverflow, it seems it also doesn't work when not using enum_column:

http://stackoverflow.com/questions/11206205/dont-get-should-validate-inclusion-of-to-work-in-rails3-2-rspec2

**Comment by jmuheim** [comment]
FactoryGirl doesn't seem to be working with enums in MySQL, too. When it's an enum, and I get a `de.activerecord.errors.messages.record_invalid` error message, and when it's a normal string, it's working.
