### ISSUE TITLE
rake db:schema:dump not generating enums in Rails 3.1.0

### ISSUE THREAD

**Issue by dotdotdotpaul** [electronick/enum_column#2]
I'm not certain, but I suspect there may be some incompatibilities between enum_column and the updated mysql2 gems that manifest in Rails 3.1.0:

In a Rails 3.0.9 project, I can "rake db:schema:dump" and get nice enum columns from the database.  In my Rails 3.1.0 project, "rake db:schema:dump" generates the same broken schema.rb files as you'd get without using the enum_column library.

I suspect that, since Rails 3.1.0 apparently includes the MySQL adapter by default, and the mysql2 gem no longer includes it (as evidenced by the fact that Rails 3.0.9 doesn't work if you've got a version of mysql2 >= 0.3) this has changed things just enough that the dumper isn't taking advantage of enum_column anymore...

I'll keep poking, but if anyone can repro this, or can figure out what I've done wrong, I'll be very happy.  :)

**Comment by dotdotdotpaul** [comment]
If it helps, I found that the monkeypatch of the Mysql2Column simplified_type call isn't being called.  Not sure why yet, but that code is definitely not getting used.

**Comment by dotdotdotpaul** [comment]
Progress.  If I invoke 'rails console', I can see the enum version of simplified_type getting called when the database is being scanned on startup.  So it's got to be some discrepancy between how Rails starts up, and how Rake starts up.

**Comment by dotdotdotpaul** [comment]
The Railtie initializer block is not being called when using rake in 3.1.0, although the enum_column.rb file is being required.  I know sod all about Railtie at the moment, but at least now I know that the various lib files are simply not being loaded by rake properly.

**Comment by dotdotdotpaul** [comment]
I tracked down the error to a change in activerecord/railties/databases.rake:

https://github.com/rails/rails/issues/2900

Will have to see if they'll accept my fix.  :)

**Comment by electronick** [comment]
This indeed happens, and the problem seems to be with wrong initialization process of the gem.

**Comment by electronick** [comment]
fixed

**Comment by dotdotdotpaul** [comment]
Using enum_column3 gem, I still have this problem.  If you're thinking of fixing it from within the gem, this is still an open issue.  I think the real problem is in Rails 3.1.0, which took out the environment initialization in the schema:dump task...

**Comment by electronick** [comment]
Hrrmm... Indeed, it could not work in such circumstances as environment is needed for detecting classes and modules enum_column gem should patch..
Don't really like the idea to wait until it will get fixed in Rails, but looking to active_record/railties/databases.rake file I see that it's possible to fix problem only by making dependency on :environment in schema:dump task..
Actually probably it's possible to make a hook on the moment when ActiveRecord::Base.establish_connection(Rails.env) runs and initialize all stuff gem need right in that moment, but I don't have any ideas right now on how to make it.

**Comment by dotdotdotpaul** [comment]
FWIW, the change which broke 3.1.0 for enum_column (and other gems used by db:schema:dump) was reverted.  So enum_column should work in 3.1.1 just fine now.

**Comment by electronick** [comment]
Good news!
