### ISSUE TITLE
Gemspec Version regressed

### ISSUE THREAD

**Issue by comp615** [electronick/enum_column#4]
Hey! I'm trying to install from git source and things worked fine until recently...I now get:

Could not find gem 'enum_column (>= 0)' in git://github.com/electronick/enum_column.git (at master).

I think in messing around with the Gemspec recently it might have broken. In addition, I looked at your commit history and it seems to go from 0.7.x to 0.1.x, I don't think that's good :-P Hopefully that's enough for you to track it down. Thanks again for the awesome gem!

**Comment by electronick** [comment]
Hello!
I've pushed it to rubygems, so now you should use command

gem 'enum_column3'

in your Gemfile.
