### ISSUE TITLE
Add / Edit enum

### ISSUE THREAD

**Issue by drhenner** [electronick/enum_column#5]
Is there a way to add enum's to existing tables?

Also If I need to add a new value to the enum what is the syntax.

I want to change an enum column from
From
status ('pending', 'active') 
 To 
status ('pending', 'active', 'canceled') 

---

and can I do something like this?

```
add_column :status, :enum, :limit => [:casual, :formal, :wild, :sports, :neutral, :colorful]
```

**Comment by electronick** [comment]
Yep, if you need to add new values and leave all old values it will work without any problems, so if you have
 status ('pending', 'active') 
and want to have
 status ('pending', 'active', 'canceled')
just make a migration like

```change_column :tasks, :status, :enum, :limit => [:pending, :active, :canceled]

``````

But if some of old values are going to be removed you should take care of objects with such values manually. For example if you need to rename some value you should do like this:

```change_column :tasks, :status, :enum, :limit => [:pending, :actice, :active]
execute('update tasks set status="active" where status="actice"')
change_column :tasks, :status, :enum, :limit => [:pending, :active]
``````
